#/*
# * Licensed to the OpenAirInterface (OAI) Software Alliance under one or more
# * contributor license agreements.  See the NOTICE file distributed with
# * this work for additional information regarding copyright ownership.
# * The OpenAirInterface Software Alliance licenses this file to You under
# * the OAI Public License, Version 1.1  (the "License"); you may not use this file
# * except in compliance with the License.
# * You may obtain a copy of the License at
# *
# *      http://www.openairinterface.org/?page_id=698
# *
# * Unless required by applicable law or agreed to in writing, software
# * distributed under the License is distributed on an "AS IS" BASIS,
# * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# * See the License for the specific language governing permissions and
# * limitations under the License.
# *-------------------------------------------------------------------------------
# * For more information about the OpenAirInterface (OAI) Software Alliance:
# *      contact@openairinterface.org
# */
#---------------------------------------------------------------------
#
# Dockerfile for the Open-Air-Interface BUILD service
#   Valid for Ubuntu 24.04
#
#---------------------------------------------------------------------

ARG BASE_IMAGE=nvcr.io/nvidia/cuda:13.0.1-devel-ubuntu24.04
ARG DOCKER_CUSTOM_IMAGE_TAG=latest
ARG NVIDIA_DRIVER_CAPABILITIES=all

FROM ran-base-cuda:${DOCKER_CUSTOM_IMAGE_TAG} AS nr-ue-base
FROM ran-build-cuda:${DOCKER_CUSTOM_IMAGE_TAG} AS nr-ue-build


#start from scratch for target executable
FROM $BASE_IMAGE AS oai-nr-ue-cuda
ARG BUILD_OPTION
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Paris
ARG BOOST_VERSION="1.83.0"

RUN apt-get update && \
    apt-get upgrade --yes && \
    apt-get install --yes \
        software-properties-common \
        procps \
        libsctp1 \
        libboost-chrono$BOOST_VERSION \
        libboost-date-time$BOOST_VERSION \
        libboost-filesystem$BOOST_VERSION \
        libboost-regex$BOOST_VERSION \
        libboost-serialization$BOOST_VERSION \
        libboost-thread$BOOST_VERSION \
        libboost-system$BOOST_VERSION \
        libboost-program-options$BOOST_VERSION \
        tzdata \
        liblapacke \
        libblas3 \
        libconfig9 \
        libforms2 \
        openssl \
        net-tools \
        gdb \
        gdbserver \
        python3 \
        python3-six \
        python3-requests \
        libusb-1.0-0 \
        iputils-ping \
        iproute2 \
        iperf3 \
        iperf \
        libyaml-cpp-dev && \
# if the --sanitize option was used to build, additional packages are required
    /bin/bash -c 'if [[ "$BUILD_OPTION" = "--sanitize" ]]; then DEBIAN_FRONTEND=noninteractive apt-get install --yes \
        libasan8 \
        libubsan1; fi' && \
    apt-get clean -y && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /opt/oai-nr-ue/bin
COPY --from=nr-ue-build \
    /oai-ran/cmake_targets/ran_build/build/nr-uesoftmodem \
    ./

COPY ./docker/scripts/nr_ue_entrypoint.sh ./entrypoint.sh
WORKDIR /opt/oai-nr-ue/etc

COPY --from=nr-ue-build \
    /oai-ran/cmake_targets/ran_build/build/liboai_eth_transpro.so \
    /oai-ran/cmake_targets/ran_build/build/librfsimulator.so \
    /oai-ran/cmake_targets/ran_build/build/liboai_usrpdevif.so \
    /oai-ran/cmake_targets/ran_build/build/libcoding.so \
    /oai-ran/cmake_targets/ran_build/build/libreceiver*.so \
    /oai-ran/cmake_targets/ran_build/build/libparams_libconfig.so \
    /oai-ran/cmake_targets/ran_build/build/libdfts.so \
    /oai-ran/cmake_targets/ran_build/build/libldpc*.so \
    /oai-ran/cmake_targets/ran_build/build/libtelnetsrv.so \
    /oai-ran/cmake_targets/ran_build/build/libtelnetsrv_ciUE.so \
    /oai-ran/cmake_targets/ran_build/build/libtelnetsrv_5Gue.so \
    /oai-ran/cmake_targets/ran_build/build/libparams_yaml.so \
    /oai-ran/cmake_targets/ran_build/build/libvrtsim.so \
    /oai-ran/cmake_targets/ran_build/build/libnrscope.so \
    /oai-ran/cmake_targets/ran_build/build/libuescope.so \
    /usr/local/lib/

# to drop in incremental build results:
#COPY ./override/lib/* /usr/local/lib/

# Now we are copying from builder-image the UHD files.
COPY --from=nr-ue-base /usr/local/bin/uhd_find_devices /usr/local/bin
COPY --from=nr-ue-base /usr/local/lib/libuhd.so.4.8.0 /usr/local/lib
COPY --from=nr-ue-base /usr/local/lib/uhd/utils/uhd_images_downloader.py /opt/oai-nr-ue/bin
COPY --from=nr-ue-base /usr/local/share/uhd/images /usr/local/share/uhd/images

# update the USRP firmware images as needed
RUN python3 /opt/oai-nr-ue/bin/uhd_images_downloader.py

RUN /bin/bash -c "ln -s /usr/local/lib/liboai_usrpdevif.so /usr/local/lib/liboai_device.so" && \
    ldconfig && \
    echo "---- ldd on nr-uesoftmodem ----" && \
    ldd /opt/oai-nr-ue/bin/nr-uesoftmodem && \
    echo "---- ldd on shared libraries ----" && \
    ldd /usr/local/lib/liboai_eth_transpro.so \
        /usr/local/lib/librfsimulator.so \
        /usr/local/lib/liboai_usrpdevif.so \
        /usr/local/lib/libcoding.so \
        /usr/local/lib/libparams_libconfig.so \
        /usr/local/lib/libdfts.so \
        /usr/local/lib/libldpc*.so \
        /usr/local/lib/libtelnetsrv.so \
        /usr/local/lib/libtelnetsrv_ciUE.so \
        /usr/local/lib/libtelnetsrv_5Gue.so \
        /usr/local/lib/libnrscope.so \
        /usr/local/lib/libuescope.so \
        /usr/local/lib/libuhd.so.4.8.0

WORKDIR /opt/oai-nr-ue
COPY --from=nr-ue-base /tini /tini
CMD ["/opt/oai-nr-ue/bin/nr-uesoftmodem"]
ENTRYPOINT ["/tini", "-v", "--", "/opt/oai-nr-ue/bin/entrypoint.sh"]
